# Generated by Django 4.2.3 on 2023-07-26 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_status', models.CharField(choices=[('Available', 'Available'), ('Unvailable', 'Unvailable'), ('No longer available', 'Suspended')], default='Unvailable', max_length=50)),
            ],
        ),
    ]
