# Generated by Django 4.2.3 on 2023-07-26 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRapp', '0002_customer_dish_feedback_dishes_feedback_order_table_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
